version: "3.7"

networks:
  gateway: {}
services:
  backend:
    build:
      dockerfile: docker/go/Dockerfile
      context: ./backend/
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./backend/:/go/src/app
    networks:
      - gateway

  frontend:
    build:
      dockerfile: docker/react/Dockerfile
      context: ./frontend/
    expose:
      - 3000
    ports:
      - 80:3000
    networks:
      - gateway